const CONSTANTS = {};

// SIGNUP REDUCERS
CONSTANTS.GET_SIGNUP_REQUEST = 'GET_SIGNUP_REQUEST';
CONSTANTS.SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
CONSTANTS.SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';
CONSTANTS.CLEAR_USER_RES = 'CLEAR_USER_RES'

// LOGIN REDUCERS
CONSTANTS.GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
CONSTANTS.LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
CONSTANTS.LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
CONSTANTS.USER_IS_LOGGEDIN = 'USER_IS_LOGGED';

// GET ALL USERS REDUCERS
CONSTANTS.GET_USER_SUCCESS = 'GET_USER_SUCCESS';
CONSTANTS.GET_USER_FAILED = 'GET_USER_FAILED';

// Orders Reducers
CONSTANTS.ADDED_QUANTITY = 'ADDED_QUANTITY';
CONSTANTS.PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
CONSTANTS.PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
CONSTANTS.PLACE_ORDER_FAILED = 'PLACE_ORDER_FAILED';
CONSTANTS.CLEAR_POST_REQUEST = 'CLEAR_POST_REQUEST';
CONSTANTS.GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST';
CONSTANTS.GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS';
CONSTANTS.GET_ALL_ORDERS_FAILED = 'GET_ALL_ORDERS_FAILED';

export default CONSTANTS;