const CONSTANTS = {};

// SIGNUP REDUCERS
CONSTANTS.GET_SIGNUP_REQUEST = 'GET_SIGNUP_REQUEST';
CONSTANTS.SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
CONSTANTS.SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';
CONSTANTS.CLEAR_USER_RES = 'CLEAR_USER_RES'

// LOGIN REDUCERS
CONSTANTS.GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
CONSTANTS.LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
CONSTANTS.LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
CONSTANTS.USER_IS_LOGGEDIN = 'USER_IS_LOGGED';

// GET ALL USERS REDUCERS
CONSTANTS.GET_USER_SUCCESS = 'GET_USER_SUCCESS';
CONSTANTS.GET_USER_FAILED = 'GET_USER_FAILED';

export default CONSTANTS;